#--- Variables --------------------------------------------------------------------------------------------
PROJECT_NAME         = Nessy
PROJECT_VERSION      = 1.0.0
PROJECT_DESCRIPTION  = Library for enumerating, generating and counting perfect binary trees
PROJECT_AUTHORS      = Nicolas Lermé
PROJECT_LICENSE      = LGPL-v3
PROJECT_LAST_RELEASE = `date`
GLOBAL_TARGET        = $(PROJECT_NAME)-$(PROJECT_VERSION)
